<#
.SYNOPSIS
  Build a VM-ready Directus .env from directus-migration.secrets.env (no prompts).

.DESCRIPTION
  Reads gitignored secrets, drops keys that must never ship to the VM (owner DB password, ADC path),
  forces DB_USER=sterile_dev, and writes directus-vm-runtime.env for migrate-directus-to-vm.ps1 -VmEnvFile.
#>
param(
  [string]$SecretsPath = (Join-Path $PSScriptRoot "directus-migration.secrets.env"),
  [string]$OutputPath  = (Join-Path $PSScriptRoot "directus-vm-runtime.env")
)

$ErrorActionPreference = "Stop"

function Read-DotEnvFile {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Secrets file not found: $Path. Copy directus-migration.secrets.env.example to directus-migration.secrets.env."
  }
  $map = @{}
  Get-Content -LiteralPath $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq "" -or $line.StartsWith("#")) { return }
    $i = $line.IndexOf("=")
    if ($i -lt 1) { return }
    $k = $line.Substring(0, $i).Trim()
    $v = $line.Substring($i + 1).Trim()
    if ($v.StartsWith('"') -and $v.EndsWith('"') -and $v.Length -ge 2) { $v = $v.Substring(1, $v.Length - 2) }
    $map[$k] = $v
  }
  return $map
}

$neverOnVm = @(
  "BS4_DEV_PASSWORD", "BS4_DEV_USER", "GOOGLE_APPLICATION_CREDENTIALS",
  "CLOUDSQL_INSTANCE", "CLOUD_SQL_PROXY_EXE", "GCP_DEPLOYER_KEY_FILE"
)

$required = @("KEY", "SECRET", "PUBLIC_URL", "DB_PASSWORD", "DB_DATABASE")
$map = Read-DotEnvFile -Path $SecretsPath

foreach ($k in $required) {
  if (-not $map.ContainsKey($k) -or [string]::IsNullOrWhiteSpace($map[$k])) {
    throw "Missing or empty required key in secrets file: $k"
  }
}

if ($map["DB_USER"] -ne "sterile_dev") {
  Write-Warning "Overriding DB_USER to sterile_dev (was: $($map['DB_USER']))."
}
$map["DB_USER"] = "sterile_dev"
if ([string]::IsNullOrWhiteSpace($map["DB_HOST"]))   { $map["DB_HOST"]   = "host.docker.internal" }
if ([string]::IsNullOrWhiteSpace($map["DB_PORT"]))   { $map["DB_PORT"]   = "5432" }
if ([string]::IsNullOrWhiteSpace($map["DB_CLIENT"])) { $map["DB_CLIENT"] = "pg" }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Generated by build-directus-vm-env.ps1 - do not commit.")
$lines.Add("# Directus DB user: sterile_dev only.")

$orderedKeys = $map.Keys | Sort-Object
foreach ($k in $orderedKeys) {
  if ($neverOnVm -contains $k) { continue }
  $v = $map[$k]
  if ($v -match '[\s#"]' -or $v -match '=') {
    $escaped = $v -replace '"', '\"'
    $lines.Add("${k}=`"${escaped}`"")
  } else {
    $lines.Add("${k}=${v}")
  }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($OutputPath, $lines.ToArray(), $utf8NoBom)
Write-Host "Wrote $OutputPath ($($lines.Count) lines)."
