DO $$ 
DECLARE
    r RECORD;
BEGIN
    FOR r IN 
        SELECT DISTINCT
            t.table_schema,
            t.table_name,
            c.column_name
        FROM information_schema.tables t
        JOIN information_schema.key_column_usage kcu ON t.table_name = kcu.table_name AND t.table_schema = kcu.table_schema
        JOIN information_schema.table_constraints tc ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
        JOIN information_schema.columns c ON c.table_name = t.table_name AND c.table_schema = t.table_schema AND c.column_name = kcu.column_name
        WHERE tc.constraint_type = 'PRIMARY KEY'
          AND t.table_schema = 'BS4Prod09Feb2026'
          AND c.data_type = 'integer'
          AND c.is_identity = 'NO'
          AND c.column_default IS NULL
          AND t.table_name NOT LIKE 'directus_%'
    LOOP
        RAISE NOTICE 'Fixing %.% ...', r.table_name, r.column_name;
        BEGIN
            -- Add identity to Postgres column
            EXECUTE 'ALTER TABLE "BS4Prod09Feb2026"."' || r.table_name || '" ALTER COLUMN "' || r.column_name || '" ADD GENERATED BY DEFAULT AS IDENTITY;';
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE '  Failed fixing %.% : %', r.table_name, r.column_name, SQLERRM;
        END;
        
    END LOOP;
END $$;
