const { Client } = require('pg');

async function run() {
  const client = new Client({
    connectionString: process.env.DB_CONNECTION_STRING || `postgres://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/${process.env.DB_DATABASE}`
  });
  await client.connect();

  const query = `
    SELECT
      t.table_name,
      c.column_name
    FROM information_schema.tables t
    JOIN information_schema.key_column_usage kcu ON t.table_name = kcu.table_name AND t.table_schema = kcu.table_schema
    JOIN information_schema.table_constraints tc ON tc.constraint_name = kcu.constraint_name
    JOIN information_schema.columns c ON c.table_name = t.table_name AND c.table_schema = t.table_schema AND c.column_name = kcu.column_name
    WHERE tc.constraint_type = 'PRIMARY KEY'
      AND t.table_schema = 'bs4_sandbox'
      AND c.data_type = 'integer'
      AND c.is_identity = 'NO'
      AND c.column_default IS NULL
      AND t.table_name NOT LIKE 'directus_%';
  `;

  const res = await client.query(query);
  console.log("Tables needing fix:", JSON.stringify(res.rows));

  for (const row of res.rows) {
    const table = row.table_name;
    const col = row.column_name;
    console.log(`Fixing ${table}.${col}...`);
    await client.query(`ALTER TABLE bs4_sandbox."${table}" ALTER COLUMN "${col}" ADD GENERATED BY DEFAULT AS IDENTITY;`);
    console.log(`  Fixed!`);
  }

  // Also need to tell Directus that these fields have auto-increment enabled in its own schema caching
  // otherwise it will keep validating them as required=true if it cached them as such.
  console.log("Updating directus_fields metadata...");
  for (const row of res.rows) {
    const table = row.table_name;
    const col = row.column_name;
    await client.query(`UPDATE bs4_sandbox.directus_fields SET has_auto_increment = true WHERE collection = $1 AND field = $2;`, [table, col]);
  }

  await client.end();
}

run().catch(console.error);
