GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "BS4Prod09Feb2026" TO sterile_dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "BS4Prod09Feb2026" TO sterile_dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "directus" TO sterile_dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "directus" TO sterile_dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO sterile_dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" TO sterile_dev;
